clear all 
close all
clc

fig = figure('Position', [200 100 1600 900]);


%% input function
h.funPanel = uipanel(fig, 'Title', 'Specify ref curve', 'FontSize',16,...
   'Position',[0.01 0.65 0.35 0.3]);
h.bgFunSpec = uibuttongroup(h.funPanel, 'Visible', 'on', ...
   'Units', 'normalized', ...
   'Position', [0 0.75 1 0.2], ...
   'SelectionChangedFcn', @bgFunSpecSelection);

% 
h.buttLoadFile = uicontrol(h.bgFunSpec, 'Style', 'radiobutton', ...
   'String', 'Load from file', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.1 0.4 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');

h.buttLoadFile = uicontrol(h.bgFunSpec, 'Style', 'radiobutton', ...
   'String', 'Specify p, r, d, e', ...
   'Units', 'normalized', ...
   'Position', [0.5 0.1 0.4 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');

h.loadPanel = uipanel(h.funPanel, 'Position', [0 0 1 0.75], ...
   'Visible', 'on');
h.specPanel = uipanel(h.funPanel, 'Position', [0 0 1 0.75], ...
   'Visible', 'off');
h.editPath = uicontrol(h.loadPanel, 'Style', 'edit', 'Units', 'normalized', ...
   'Position',[0.05 0.35 0.7 0.3], 'String', pwd, 'FontSize', 12);
[figOpen, cmap] = imread(fullfile('figures', 'openFile.png'));
h.pbLoadFile = uicontrol(h.loadPanel, 'Style', 'pushbutton', ...
   'Units', 'normalized', 'Position',[0.8 0.35 0.1 0.3], 'String', '...', ...
   'FontSize', 12, 'CData', figOpen, 'Callback', @loadFile);


%% VF solver settings
h.inputPanel = uipanel(fig, 'Title', 'Specify VF settings', 'FontSize',16,...
   'Position',[0.01 0.05 0.35 0.5]);
h.bgVFTypeSpec = uibuttongroup(h.inputPanel, 'Visible', 'on', ...
   'Units', 'normalized', ...
   'Position', [0 0.85 1 0.12], ...
   'SelectionChangedFcn', @bgVFTypeSpecSelection);

% 
h.buttAutoVF = uicontrol(h.bgVFTypeSpec, 'Style', 'radiobutton', ...
   'String', 'Automatic VF', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.1 0.4 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');

h.buttUserVF = uicontrol(h.bgVFTypeSpec, 'Style', 'radiobutton', ...
   'String', 'User-defined VF', ...
   'Units', 'normalized', ...
   'Position', [0.5 0.1 0.4 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');

h.autoVFPanel = uipanel(h.inputPanel, 'Position', [0 0 1 0.85], ...
   'Visible', 'on');
h.userVFPanel = uipanel(h.inputPanel, 'Position', [0 0 1 0.85], ...
   'Visible', 'off');


%% AutoVF
h.pbRunAutoVF = uicontrol(h.autoVFPanel, 'Style', 'pushbutton', ...
   'String', 'Run VF', ...
   'Units', 'normalized', ...
   'Position', [0.3 0.05 0.4 0.1], ...
   'FontSize', 14, ...
   'Callback', @runAutoVF);

textBackColor = [0.7 0.7 0.7];
h.autoTextRmse = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', 'Required rmse', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.2 0.3 0.1], ...
   'FontSize', 14, ...
   'BackgroundColor', textBackColor, ...
   'Enable', 'off');
h.autoEditRmse = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', '1e-5', ...
   'Units', 'normalized', ...
   'Position', [0.6 0.2 0.3 0.1], ...
   'FontSize', 14);

h.autoTextMaxT = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', 'Max # trials', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.3 0.3 0.1], ...
   'FontSize', 14, ...
   'BackgroundColor', textBackColor, ...
   'Enable', 'off');
h.autoEditMaxT = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', '20', ...
   'Units', 'normalized', ...
   'Position', [0.6 0.3 0.3 0.1], ...
   'FontSize', 14);

h.autoTextNIters = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', '# iterations', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.4 0.3 0.1], ...
   'FontSize', 14, ...
   'BackgroundColor', textBackColor, ...
   'Enable', 'off');
h.autoEditNIters = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', '1', ...
   'Units', 'normalized', ...
   'Position', [0.6 0.4 0.3 0.1], ...
   'FontSize', 14);

h.autoTextPoleType = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', 'Init. poles type', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.5 0.3 0.1], ...
   'FontSize', 14, ...
   'BackgroundColor', textBackColor, ...
   'Enable', 'off');
h.autoPopupPoleType = uicontrol(h.autoVFPanel, 'Style', 'popupmenu', ...
   'String', {'complex', 'real'}, ...
   'Units', 'normalized', ...
   'Position', [0.6 0.5 0.3 0.1], ...
   'FontSize', 14);

h.autoTextDistr = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', 'Init. pole sistribution', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.6 0.3 0.1], ...
   'FontSize', 14, ...
   'BackgroundColor', textBackColor, ...
   'Enable', 'off');
h.autoPopupDistr = uicontrol(h.autoVFPanel, 'Style', 'popupmenu', ...
   'String', {'linear', 'logarithmic'}, ...
   'Units', 'normalized', ...
   'Position', [0.6 0.6 0.3 0.1], ...
   'FontSize', 14);

h.autoTextResChoice = uicontrol(h.autoVFPanel, 'Style', 'edit', ...
   'String', 'Choice type', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.7 0.3 0.1], ...
   'FontSize', 14, ...
   'BackgroundColor', textBackColor, ...
   'Enable', 'off');
h.autoPopupResChoice = uicontrol(h.autoVFPanel, 'Style', 'popupmenu', ...
   'String', {'first', 'best'}, ...
   'Units', 'normalized', ...
   'Position', [0.6 0.7 0.3 0.1], ...
   'FontSize', 14);

%% 

%% plot spec
h.plotSpecPanel = uipanel(fig, 'Title', 'Specify plot settings', ...
   'FontSize', 16, 'Position', [0.45 0.8 0.5 0.15]);
h.bgPlotSpec = uibuttongroup(h.plotSpecPanel, ...
   'Units', 'normalized', ...
   'Position', [0 0.55 1 0.4], ...
   'SelectionChangedFcn', @bgPlotSpecFun);
h.buttAbs = uicontrol(h.bgPlotSpec, 'Style', 'radiobutton', ...
   'String', 'Abs', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.1 0.3 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');
h.buttReal = uicontrol(h.bgPlotSpec, 'Style', 'radiobutton', ...
   'String', 'Real', ...
   'Units', 'normalized', ...
   'Position', [0.4 0.1 0.3 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');
h.buttImag = uicontrol(h.bgPlotSpec, 'Style', 'radiobutton', ...
   'String', 'Imag', ...
   'Units', 'normalized', ...
   'Position', [0.7 0.1 0.3 0.8], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off');

h.buttLogX = uicontrol(h.plotSpecPanel, 'Style', 'radiobutton', ...
   'String', 'log x-axis', ...
   'Units', 'normalized', ...
   'Position', [0.2 0.1 0.3 0.3], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off', ...
   'Callback', @bgPlotSpecFun);

h.buttLogY = uicontrol(h.plotSpecPanel, 'Style', 'radiobutton', ...
   'String', 'log y-axis', ...
   'Units', 'normalized', ...
   'Position', [0.55 0.1 0.3 0.3], ...
   'FontSize', 14, ...
   'HandleVisibility', 'off', ...
   'Callback', @bgPlotSpecFun);

%% axes
h.axes = axes(fig, 'Units', 'normalized', ...
   'Position', [0.45 0.3 0.5 0.45], 'FontSize', 16, ...
   'NextPlot', 'replacechildren');
grid on
xlabel(h.axes, '$f$ [Hz]', 'Interpreter', 'latex')
ylabel(h.axes, '$fun$ [-]', 'Interpreter', 'latex')


%% results display
h.resultsPanel = uipanel(fig, 'Title', 'Results', ...
   'FontSize', 16, 'Position', [0.45 0.05 0.5 0.15]);
h.textResRmse = uicontrol(h.resultsPanel, 'Style', 'text', ...
   'String', 'rmse = ?', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.6 0.3 0.3], ...
   'FontSize', 14);
h.textResNPoles = uicontrol(h.resultsPanel, 'Style', 'text', ...
   'String', '# poles N = ?', ...
   'Units', 'normalized', ...
   'Position', [0.1 0.2 0.3 0.3], ...
   'FontSize', 14);



setappdata(fig, 'handles', h)